// Insurance Claims seed — models the real claims lifecycle (FNOL → Triage →
// Adjusting → Approval → Settlement → Closed) with the Claims AI agent's
// outputs (document extraction, triage severity, fraud score, suggested
// reserve). The agent proposes; the officer decides; money is approval-gated.
const M = (amount, currency = 'USD') => ({
    amountMinor: BigInt(Math.round(amount * 100)),
    currency,
});
const ev = (id, name, kind, sizeText) => ({ id, name, kind, sizeText });
export const seedClaims = [
    {
        id: 'CLM-2025-00412',
        claimant: 'Jean-Paul Niyonzima',
        policyNumber: 'MOT-88231',
        type: 'motor',
        stage: 'triage',
        incidentDate: '2025-05-12',
        reportedDate: '2025-05-13',
        description: 'Rear-end collision at Kimironko roundabout; bumper and tail-light damage.',
        claimedAmount: M(2400),
        deductible: M(200),
        aiSummary: 'Single-vehicle rear-end collision. Police report and 4 photos attached. Damage consistent with a low-speed impact; repair quote from approved garage included.',
        triageSeverity: 'low',
        triageFastTrack: true,
        fraudScore: 12,
        fraudFlags: [],
        suggestedReserve: M(2200),
        suggestedSettlement: M(2200),
        reserve: M(2200),
        evidence: [ev('cev-1', 'Police report PR-5521.pdf', 'statement', '420 KB'), ev('cev-2', 'Repair quote — Kigali Auto.pdf', 'invoice', '180 KB')],
        assignedTo: 'James Okello',
        slaText: 'SLA 2d',
        paymentReconciled: null,
        coverageOk: true,
    },
    {
        id: 'CLM-2025-00408',
        claimant: 'Aline Uwimana',
        policyNumber: 'HLT-44120',
        type: 'health',
        stage: 'adjusting',
        incidentDate: '2025-05-08',
        reportedDate: '2025-05-09',
        description: 'Inpatient surgery — appendectomy at King Faisal Hospital.',
        claimedAmount: M(8600),
        deductible: M(0),
        aiSummary: 'Inpatient surgical claim. Hospital invoice, discharge summary and pre-authorization on file. Procedure covered under the policy; amounts within network tariff.',
        triageSeverity: 'medium',
        triageFastTrack: false,
        fraudScore: 18,
        fraudFlags: [],
        suggestedReserve: M(8600),
        suggestedSettlement: M(8200),
        reserve: M(8600),
        evidence: [ev('cev-3', 'Hospital invoice.pdf', 'invoice', '610 KB'), ev('cev-4', 'Discharge summary.pdf', 'statement', '340 KB'), ev('cev-5', 'Pre-authorization.pdf', 'contract', '120 KB')],
        assignedTo: 'James Okello',
        slaText: 'SLA 3d',
        paymentReconciled: null,
        coverageOk: true,
    },
    {
        id: 'CLM-2025-00401',
        claimant: 'Eric Mugisha',
        policyNumber: 'PRP-20984',
        type: 'property',
        stage: 'approval',
        incidentDate: '2025-05-02',
        reportedDate: '2025-05-03',
        description: 'Warehouse fire — stock and structural damage, Gikondo industrial zone.',
        claimedAmount: M(184000),
        deductible: M(5000),
        aiSummary: 'Major property loss. Loss-adjuster report estimates structural damage and destroyed inventory. Fire-brigade report confirms accidental electrical cause. High-value — over Finance Lead limit, requires dual approval.',
        triageSeverity: 'critical',
        triageFastTrack: false,
        fraudScore: 34,
        fraudFlags: ['High value', 'Inventory valuation pending second estimate'],
        suggestedReserve: M(179000),
        suggestedSettlement: M(176500),
        reserve: M(180000),
        evidence: [ev('cev-6', 'Loss adjuster report.pdf', 'statement', '2.1 MB'), ev('cev-7', 'Fire brigade report.pdf', 'statement', '480 KB'), ev('cev-8', 'Inventory schedule.xlsx', 'invoice', '210 KB')],
        assignedTo: 'James Okello',
        slaText: 'SLA 5d',
        paymentReconciled: null,
        coverageOk: true,
    },
    {
        id: 'CLM-2025-00395',
        claimant: 'Grace Keza',
        policyNumber: 'MOT-77310',
        type: 'motor',
        stage: 'triage',
        incidentDate: '2025-05-11',
        reportedDate: '2025-05-15',
        description: 'Theft of vehicle accessories and reported windshield damage.',
        claimedAmount: M(3200),
        deductible: M(200),
        aiSummary: 'Reported 4 days after incident. Two similar claims on this policy in the last 90 days. Photos show inconsistent damage angles; no police report attached. Recommend SIU review before proceeding.',
        triageSeverity: 'high',
        triageFastTrack: false,
        fraudScore: 78,
        fraudFlags: ['3rd claim in 90 days', 'Late reporting (4 days)', 'No police report', 'Inconsistent photo evidence'],
        suggestedReserve: M(0),
        suggestedSettlement: M(0),
        reserve: M(1500),
        evidence: [ev('cev-9', 'Claim form.pdf', 'statement', '90 KB'), ev('cev-10', 'Photos.png', 'receipt', '1.4 MB')],
        assignedTo: 'James Okello',
        slaText: 'SIU review',
        paymentReconciled: null,
        coverageOk: false,
    },
    {
        id: 'CLM-2025-00370',
        claimant: 'Patrick Habiyaremye',
        policyNumber: 'HLT-41902',
        type: 'health',
        stage: 'settlement',
        incidentDate: '2025-04-28',
        reportedDate: '2025-04-29',
        description: 'Outpatient treatment and prescription — covered, approved.',
        claimedAmount: M(640),
        deductible: M(0),
        aiSummary: 'Outpatient claim approved at $620. Payment issued to provider; matching against the bank feed.',
        triageSeverity: 'low',
        triageFastTrack: true,
        fraudScore: 8,
        fraudFlags: [],
        suggestedReserve: M(640),
        suggestedSettlement: M(620),
        reserve: M(640),
        evidence: [ev('cev-11', 'Pharmacy invoice.pdf', 'invoice', '70 KB')],
        assignedTo: 'James Okello',
        slaText: 'Paid · reconciling',
        paymentReconciled: false,
        coverageOk: true,
    },
    {
        id: 'CLM-2025-00355',
        claimant: 'Diane Ingabire',
        policyNumber: 'MOT-69521',
        type: 'motor',
        stage: 'closed',
        incidentDate: '2025-04-20',
        reportedDate: '2025-04-20',
        description: 'Windshield replacement — settled and reconciled.',
        claimedAmount: M(480),
        deductible: M(100),
        aiSummary: 'Settled at $380 (after deductible). Payment matched to bank statement; claim closed.',
        triageSeverity: 'low',
        triageFastTrack: true,
        fraudScore: 5,
        fraudFlags: [],
        suggestedReserve: M(380),
        suggestedSettlement: M(380),
        reserve: M(380),
        evidence: [ev('cev-12', 'Repair invoice.pdf', 'invoice', '110 KB')],
        assignedTo: 'James Okello',
        slaText: 'Closed',
        paymentReconciled: true,
        coverageOk: true,
    },
];
// ── Pipeline + portfolio stats ──────────────────────────────────────────────
export const CLAIM_STAGES = [
    { id: 'fnol', label: 'FNOL' },
    { id: 'triage', label: 'Triage' },
    { id: 'adjusting', label: 'Adjusting' },
    { id: 'approval', label: 'Approval' },
    { id: 'settlement', label: 'Settlement' },
    { id: 'closed', label: 'Closed' },
];
export const seedClaimsStats = {
    openClaims: 38,
    totalReserves: M(1240000),
    avgCycleDays: 6.4,
    fraudFlagged: 4,
    leakagePrevented: M(86400),
    // larger period counts for the pipeline band (the table is a snapshot)
    pipeline: { fnol: 5, triage: 12, adjusting: 9, approval: 4, settlement: 6, closed: 142 },
};
