import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search } from 'lucide-react';
import { GlassSurface, MoneyCell, cn } from '../../design-system';
import { useClaimsStore } from '../../state/claimsStore';
import { SEVERITY_TONE, TYPE_ICON, TYPE_TONE, fraudTone } from './claimMeta';
export function ClaimsQueue({ selectedId, onSelect, stageFilter, }) {
    const claims = useClaimsStore((s) => s.claims);
    const filtered = stageFilter === 'all' ? claims : claims.filter((c) => c.stage === stageFilter);
    return (_jsxs(GlassSurface, { tone: "strong", className: "flex h-full min-h-0 flex-col", children: [_jsxs("header", { className: "flex items-center justify-between gap-3 px-5 pt-5", children: [_jsx("h2", { className: "font-display text-[16px] font-bold text-ink", children: "Claims" }), _jsx("span", { className: "text-[11px] font-semibold text-ink-muted tabular", children: filtered.length })] }), _jsx("div", { className: "px-5 pt-3", children: _jsxs("div", { className: "flex h-10 items-center gap-2.5 rounded-xl bg-white/70 px-3.5 ring-1 ring-white/70", children: [_jsx(Search, { className: "size-4 text-ink-muted" }), _jsx("input", { type: "search", placeholder: "Search claimant, policy, claim #\u2026", className: "w-full bg-transparent text-[13px] text-ink placeholder:text-ink-muted focus:outline-none" })] }) }), _jsxs("ul", { className: "scrollbar-thin mt-3 flex min-h-0 flex-1 flex-col gap-1.5 overflow-y-auto px-3 pb-3", children: [filtered.map((c) => (_jsx(ClaimRow, { claim: c, selected: c.id === selectedId, onSelect: () => onSelect(c.id) }, c.id))), filtered.length === 0 ? (_jsx("li", { className: "grid place-items-center py-12 text-center text-[12.5px] text-ink-muted", children: "No claims in this stage." })) : null] })] }));
}
function ClaimRow({ claim: c, selected, onSelect }) {
    const Icon = TYPE_ICON[c.type];
    return (_jsx("li", { children: _jsxs("button", { type: "button", onClick: onSelect, className: cn('flex w-full items-start gap-3 rounded-2xl px-3 py-3 text-left transition-colors', selected ? 'bg-white shadow-glass-soft ring-1 ring-white/85' : 'bg-white/40 hover:bg-white/70'), children: [_jsx("span", { className: cn('grid size-10 shrink-0 place-items-center rounded-xl', TYPE_TONE[c.type]), children: _jsx(Icon, { className: "size-[18px]" }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "truncate text-[13px] font-bold text-ink", children: c.claimant }), _jsx("span", { className: cn('shrink-0 rounded-full px-1.5 py-0.5 text-[9px] font-bold uppercase', SEVERITY_TONE[c.triageSeverity]), children: c.triageSeverity })] }), _jsxs("p", { className: "truncate text-[11px] text-ink-muted", children: [c.id, " \u00B7 ", c.policyNumber, " \u00B7 ", c.slaText] }), _jsxs("div", { className: "mt-1 flex items-center gap-2", children: [_jsxs("span", { className: cn('rounded-full px-1.5 py-0.5 text-[9.5px] font-bold', fraudTone(c.fraudScore)), children: ["Fraud ", c.fraudScore] }), c.fraudFlags.length > 0 ? _jsxs("span", { className: "text-[10px] font-medium text-danger", children: [c.fraudFlags.length, " flag", c.fraudFlags.length > 1 ? 's' : ''] }) : null] })] }), _jsx(MoneyCell, { amount: c.claimedAmount, size: "sm", className: "shrink-0 font-bold !text-[13px]" })] }) }));
}
