import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertTriangle, FileText, Gauge, Sparkles } from 'lucide-react';
import { GlassSurface, MoneyCell, cn } from '../../design-system';
import { SEVERITY_TONE, fraudTone } from './claimMeta';
// The Claims AI agent's output — document extraction, triage, fraud score and
// a suggested reserve. It PROPOSES; the officer decides (never silent on money).
export function ClaimsAgentPanel({ claim }) {
    return (_jsxs(GlassSurface, { tone: "strong", className: "flex flex-col gap-4 bg-gradient-to-br from-ai-soft/70 to-white/40 p-5 ring-1 ring-ai/15", children: [_jsxs("header", { className: "flex items-center gap-2", children: [_jsx("span", { className: "grid size-8 place-items-center rounded-xl bg-gradient-to-br from-ai to-brand text-white", children: _jsx(Sparkles, { className: "size-4" }) }), _jsx("h3", { className: "font-display text-[15px] font-bold text-ink", children: "Claims agent" }), _jsx("span", { className: "ml-auto rounded-full bg-white/70 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-ink-muted ring-1 ring-white/70", children: "AI proposes \u00B7 you decide" })] }), _jsxs("div", { className: "rounded-2xl bg-white/60 p-3.5 ring-1 ring-white/60", children: [_jsxs("p", { className: "mb-1 inline-flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wider text-ink-muted", children: [_jsx(FileText, { className: "size-3.5" }), " Extracted summary"] }), _jsx("p", { className: "text-[13px] leading-relaxed text-ink", children: claim.aiSummary })] }), _jsxs("div", { className: "grid grid-cols-1 gap-3 @2xl:grid-cols-3", children: [_jsxs(Tile, { label: "Triage severity", icon: _jsx(Gauge, { className: "size-4" }), children: [_jsx("span", { className: cn('inline-flex rounded-full px-2.5 py-1 text-[12px] font-bold uppercase', SEVERITY_TONE[claim.triageSeverity]), children: claim.triageSeverity }), _jsx("span", { className: "mt-1 block text-[11px] text-ink-muted", children: claim.triageFastTrack ? 'Eligible for fast-track' : 'Standard handling' })] }), _jsxs(Tile, { label: "Fraud score", icon: _jsx(AlertTriangle, { className: "size-4" }), children: [_jsxs("span", { className: cn('inline-flex items-baseline gap-1 rounded-full px-2.5 py-1 text-[12px] font-bold', fraudTone(claim.fraudScore)), children: [_jsx("span", { className: "font-display text-base tabular", children: claim.fraudScore }), "/100"] }), claim.fraudFlags.length > 0 ? (_jsx("ul", { className: "mt-1.5 space-y-0.5", children: claim.fraudFlags.slice(0, 3).map((f) => (_jsxs("li", { className: "text-[10.5px] font-medium text-danger", children: ["\u2022 ", f] }, f))) })) : (_jsx("span", { className: "mt-1 block text-[11px] text-ink-muted", children: "No fraud indicators" }))] }), _jsxs(Tile, { label: "Suggested reserve", icon: _jsx(Sparkles, { className: "size-4" }), children: [_jsx(MoneyCell, { amount: claim.suggestedReserve, size: "lg", className: "!text-xl" }), _jsxs("span", { className: "mt-1 block text-[11px] text-ink-muted", children: ["Settlement est. ", _jsx(MoneyCell, { amount: claim.suggestedSettlement, size: "sm", className: "!text-[11px] font-semibold" })] })] })] })] }));
}
function Tile({ label, icon, children }) {
    return (_jsxs("div", { className: "rounded-2xl bg-white/60 p-3.5 ring-1 ring-white/60", children: [_jsxs("p", { className: "mb-2 inline-flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wider text-ink-muted", children: [icon, " ", label] }), children] }));
}
