import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as Dialog from '@radix-ui/react-dialog';
import { Download, FileSpreadsheet, FileText, Image as ImageIcon, Maximize2, Printer, ShieldCheck, X, ZoomIn, ZoomOut, } from 'lucide-react';
import { GlassSurface, IconButton } from '../../design-system';
import { useDocViewerStore } from '../../state/docViewerStore';
import { toast } from '../../state/toastStore';
// The dedicated document viewer — a modal "view box" used everywhere a doc can
// be opened (evidence, audit packs, statements). The preview is representative
// (real bytes come from the object store later); the chrome (zoom, download,
// print, page ref, evidence seal) is real.
export function DocViewer() {
    const doc = useDocViewerStore((s) => s.doc);
    const close = useDocViewerStore((s) => s.close);
    const open = doc !== null;
    const ext = doc?.name.split('.').pop()?.toUpperCase() ?? 'PDF';
    const Icon = ext === 'XLSX' || ext === 'CSV' ? FileSpreadsheet : ext === 'PNG' || ext === 'JPG' ? ImageIcon : FileText;
    return (_jsx(Dialog.Root, { open: open, onOpenChange: (o) => !o && close(), children: _jsxs(Dialog.Portal, { children: [_jsx(Dialog.Overlay, { className: "fixed inset-0 z-[90] bg-ink/30 backdrop-blur-sm data-[state=open]:animate-in data-[state=open]:fade-in" }), _jsxs(Dialog.Content, { className: "fixed left-1/2 top-1/2 z-[95] flex h-[82vh] w-[min(880px,92vw)] -translate-x-1/2 -translate-y-1/2 flex-col overflow-hidden rounded-3xl border border-glass-border-strong bg-glass-strong shadow-glass-lg backdrop-blur-glass-lg focus:outline-none", "aria-describedby": undefined, children: [_jsxs("header", { className: "flex items-center gap-3 border-b border-white/55 px-5 py-3.5", children: [_jsx("span", { className: "grid size-10 shrink-0 place-items-center rounded-xl bg-danger-soft text-danger", children: _jsx(Icon, { className: "size-5" }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx(Dialog.Title, { className: "truncate font-display text-[15px] font-bold text-ink", children: doc?.name }), _jsx("p", { className: "truncate text-[11.5px] text-ink-muted", children: [doc?.kind, doc?.sizeText, doc?.pageRef, doc?.context].filter(Boolean).join(' · ') })] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx(IconButton, { variant: "ghost", size: "sm", label: "Zoom out", children: _jsx(ZoomOut, {}) }), _jsx(IconButton, { variant: "ghost", size: "sm", label: "Zoom in", children: _jsx(ZoomIn, {}) }), _jsx(IconButton, { variant: "ghost", size: "sm", label: "Fit", children: _jsx(Maximize2, {}) }), _jsx("span", { className: "mx-1 h-5 w-px bg-ink/10" }), _jsx(IconButton, { variant: "ghost", size: "sm", label: "Print", onClick: () => toast({ tone: 'info', title: 'Sent to print', body: doc?.name }), children: _jsx(Printer, {}) }), _jsx(IconButton, { variant: "glass", size: "sm", label: "Download", onClick: () => toast({ tone: 'success', title: 'Download started', body: doc?.name }), children: _jsx(Download, {}) }), _jsx(Dialog.Close, { asChild: true, children: _jsx(IconButton, { variant: "ghost", size: "sm", label: "Close", children: _jsx(X, {}) }) })] })] }), _jsx("div", { className: "scrollbar-thin flex-1 overflow-auto bg-[#e9edf6] p-6", children: _jsx(GlassSurface, { noBlur: true, tone: "strong", className: "mx-auto w-[640px] max-w-full bg-white p-10 shadow-glass-lg", children: _jsx(MockPage, { name: doc?.name ?? '', context: doc?.context, ext: ext }) }) }), _jsxs("footer", { className: "flex items-center gap-2 border-t border-white/55 px-5 py-2.5", children: [_jsx(ShieldCheck, { className: "size-4 text-success" }), _jsx("span", { className: "text-[11.5px] font-semibold text-ink-soft", children: "Evidence document \u00B7 integrity verified \u00B7 opening is logged to the audit trail" })] })] })] }) }));
}
// A representative document body so the viewer reads like a real one.
function MockPage({ name, context, ext }) {
    if (ext === 'XLSX' || ext === 'CSV') {
        return (_jsxs("div", { className: "font-mono text-[11px]", children: [_jsx("p", { className: "mb-4 font-display text-base font-bold text-ink", children: name }), _jsx("div", { className: "overflow-hidden rounded-lg ring-1 ring-ink/10", children: Array.from({ length: 9 }).map((_, r) => (_jsx("div", { className: `grid grid-cols-4 ${r === 0 ? 'bg-ink/5 font-bold' : r % 2 ? 'bg-ink/[0.02]' : ''}`, children: Array.from({ length: 4 }).map((__, c) => (_jsx("span", { className: "truncate border-b border-r border-ink/10 px-2 py-1.5 text-ink-soft", children: r === 0 ? ['Date', 'Reference', 'Party', 'Amount'][c] : _jsx("span", { className: "inline-block h-2 w-[70%] rounded bg-ink/10" }) }, c))) }, r))) })] }));
    }
    return (_jsxs("div", { children: [_jsxs("div", { className: "flex items-start justify-between border-b-2 border-ink/80 pb-4", children: [_jsxs("div", { children: [_jsx("p", { className: "font-display text-xl font-bold text-ink", children: name.replace(/\.[^.]+$/, '') }), context ? _jsx("p", { className: "text-[12px] text-ink-muted", children: context }) : null] }), _jsxs("div", { className: "text-right text-[10px] uppercase tracking-wider text-ink-muted", children: ["Kora", _jsx("br", {}), "Evidence preview"] })] }), _jsx("div", { className: "mt-6 space-y-2.5", children: [100, 92, 96, 70].map((w, i) => (_jsx("div", { className: "h-2.5 rounded bg-ink/10", style: { width: `${w}%` } }, i))) }), _jsx("div", { className: "mt-6 grid grid-cols-2 gap-4", children: Array.from({ length: 4 }).map((_, i) => (_jsxs("div", { className: "rounded-lg bg-ink/[0.03] p-3 ring-1 ring-ink/10", children: [_jsx("div", { className: "mb-2 h-2 w-1/3 rounded bg-ink/15" }), _jsx("div", { className: "h-2 w-2/3 rounded bg-ink/10" })] }, i))) }), _jsx("div", { className: "mt-6 space-y-2.5", children: [88, 100, 84, 95, 60].map((w, i) => (_jsx("div", { className: "h-2.5 rounded bg-ink/10", style: { width: `${w}%` } }, i))) }), _jsxs("div", { className: "mt-8 flex items-end justify-between border-t border-ink/15 pt-4", children: [_jsx("div", { className: "h-10 w-32 rounded bg-ink/[0.04] ring-1 ring-ink/10" }), _jsx("p", { className: "text-[10px] text-ink-muted", children: "Page 1 of 1" })] })] }));
}
