import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// The glass-sphere brand mark + "BUSINESS OS" wordmark. Inline SVG so it
// stays crisp at any density and inherits color from the surrounding text.
export function KoraLogo({ className }) {
    return (_jsx("div", { className: className, children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(KoraGlyph, { className: "size-12 shrink-0" }), _jsxs("div", { className: "flex flex-col leading-none", children: [_jsx("span", { className: "font-display text-2xl font-extrabold tracking-tight text-ink", children: "KORA" }), _jsx("span", { className: "text-[10px] font-semibold tracking-[0.22em] text-ink-muted", children: "BUSINESS OS" })] })] }) }));
}
export function KoraGlyph({ className }) {
    return (_jsxs("svg", { viewBox: "0 0 48 48", className: className, "aria-hidden": true, children: [_jsxs("defs", { children: [_jsxs("radialGradient", { id: "kora-sphere", cx: "35%", cy: "30%", r: "80%", children: [_jsx("stop", { offset: "0%", stopColor: "#dfe7ff" }), _jsx("stop", { offset: "35%", stopColor: "#8ea4ff" }), _jsx("stop", { offset: "75%", stopColor: "#5a78f5" }), _jsx("stop", { offset: "100%", stopColor: "#3340c0" })] }), _jsxs("radialGradient", { id: "kora-sheen", cx: "30%", cy: "22%", r: "40%", children: [_jsx("stop", { offset: "0%", stopColor: "rgba(255,255,255,0.9)" }), _jsx("stop", { offset: "100%", stopColor: "rgba(255,255,255,0)" })] }), _jsxs("linearGradient", { id: "kora-stroke", x1: "0", y1: "0", x2: "1", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "#ffffff", stopOpacity: "0.85" }), _jsx("stop", { offset: "100%", stopColor: "#ffffff", stopOpacity: "0.15" })] })] }), _jsx("circle", { cx: "24", cy: "24", r: "20", fill: "url(#kora-sphere)" }), _jsx("circle", { cx: "24", cy: "24", r: "20", fill: "url(#kora-sheen)" }), _jsx("path", { d: "M16 14v20M16 24l11-10M16 24l11 10", fill: "none", stroke: "url(#kora-stroke)", strokeWidth: "3.2", strokeLinecap: "round", strokeLinejoin: "round" }), _jsx("circle", { cx: "24", cy: "24", r: "19.5", fill: "none", stroke: "rgba(255,255,255,0.5)", strokeWidth: "0.5" })] }));
}
