import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from '@tanstack/react-router';
import { CheckCircle2, Lock, XCircle } from 'lucide-react';
import { GlassSurface, ProgressRing, cn } from '../../design-system';
import { seedCloseTasks } from '../../seed/financeLeadClose';
export function CloseStatusCard({ tasks = seedCloseTasks }) {
    const done = tasks.filter((task) => task.done).length;
    const blocked = tasks.filter((task) => task.blocked).length;
    const pct = done / tasks.length;
    const next = tasks.filter((task) => !task.done).slice(0, 4);
    return (_jsxs(GlassSurface, { tone: "strong", className: "flex h-full flex-col gap-4 p-6", children: [_jsxs("header", { className: "flex items-center justify-between gap-3", children: [_jsx("h3", { className: "font-display text-base font-bold text-ink", children: "May month-end close" }), _jsx(Link, { to: "/audit", className: "text-xs font-semibold text-brand hover:text-brand-ink", children: "Open Controls & Close" })] }), _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(ProgressRing, { value: pct, size: 104, thickness: 11, color: "#4361ee", children: _jsxs("div", { className: "flex flex-col", children: [_jsxs("span", { className: "font-display text-xl font-bold text-ink tabular", children: [done, "/", tasks.length] }), _jsx("span", { className: "text-[9.5px] font-semibold uppercase tracking-wider text-ink-muted", children: "tasks" })] }) }), _jsxs("div", { className: "flex-1", children: [_jsxs("p", { className: "font-display text-2xl font-bold text-ink", children: [Math.round(pct * 100), "%"] }), _jsxs("p", { className: "text-[12px] text-ink-muted", children: [tasks.length - done, " remaining \u00B7 ", blocked, " blocked \u00B7 due in 3 days"] }), _jsxs("span", { className: cn('mt-2 inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold', blocked > 0 ? 'bg-warning-soft text-warning' : 'bg-success-soft text-success'), children: [_jsx(Lock, { className: "size-3.5" }), " ", blocked > 0 ? 'Resolve blockers to lock' : 'On track to lock'] })] })] }), _jsx("ul", { className: "grid flex-1 grid-cols-1 gap-2 @2xl:grid-cols-2", children: next.map((task) => (_jsxs("li", { className: "flex items-center gap-2.5 rounded-2xl bg-white/55 p-3 ring-1 ring-white/60", children: [task.blocked ? _jsx(XCircle, { className: "size-4 shrink-0 text-danger" }) : _jsx(CheckCircle2, { className: "size-4 shrink-0 text-ink-muted" }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "truncate text-[12.5px] font-semibold text-ink", children: task.label }), _jsx("p", { className: "truncate text-[10.5px] text-ink-muted", children: task.owner })] })] }, task.id))) })] }));
}
