import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronDown, Info, Maximize2, MoreHorizontal } from 'lucide-react';
import { AreaChart, GlassSurface, MoneyCell } from '../../design-system';
export function CashFlowCard({ cashFlow }) {
    const { netPosition, inflow, outflow, net, series, xLabels } = cashFlow;
    return (_jsxs(GlassSurface, { tone: "strong", className: "flex h-full flex-col gap-5 p-6", children: [_jsxs("header", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h3", { className: "font-display text-lg font-semibold text-ink", children: "Cash Flow Overview" }), _jsx(Info, { className: "size-3.5 text-ink-muted" })] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsxs("button", { type: "button", className: "inline-flex h-8 items-center gap-1.5 rounded-xl bg-white/70 px-3 text-xs font-semibold text-ink-soft ring-1 ring-white/80 hover:bg-white", children: ["This Month ", _jsx(ChevronDown, { className: "size-3" })] }), _jsx(RoundIcon, { label: "Expand", children: _jsx(Maximize2, { className: "size-4" }) }), _jsx(RoundIcon, { label: "More", children: _jsx(MoreHorizontal, { className: "size-4" }) })] })] }), _jsxs("div", { className: "grid min-h-0 flex-1 grid-cols-[minmax(200px,240px)_1fr] grid-rows-1 gap-4", children: [_jsxs("div", { className: "flex flex-col gap-4", children: [_jsxs("div", { children: [_jsx(MoneyCell, { amount: netPosition, size: "xl", className: "!text-[26px]" }), _jsx("p", { className: "mt-0.5 text-xs font-medium text-ink-muted", children: "Net Cash Position" })] }), _jsx(LegendRow, { color: "#4361ee", label: "Cash Inflow", money: inflow }), _jsx(LegendRow, { color: "#9a8ce8", label: "Cash Outflow", money: outflow }), _jsx(LegendRow, { color: "#16a37b", label: "Net Cash Flow", money: net })] }), _jsx("div", { className: "min-h-0 min-w-0", children: _jsx(AreaChart, { xLabels: [...xLabels], series: series.map((s) => ({ ...s, data: [...s.data] })), height: "100%" }) })] })] }));
}
function LegendRow({ color, label, money }) {
    return (_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("span", { className: "grid size-3 place-items-center rounded-full", style: { backgroundColor: color }, children: _jsx("span", { className: "size-1.5 rounded-full bg-white" }) }), _jsxs("div", { className: "flex flex-col leading-tight", children: [_jsx("span", { className: "text-[11px] font-medium text-ink-muted", children: label }), _jsx(MoneyCell, { amount: money, size: "sm", className: "font-semibold !text-[13.5px]" })] })] }));
}
function RoundIcon({ label, children }) {
    return (_jsx("button", { type: "button", "aria-label": label, title: label, className: "grid size-8 place-items-center rounded-xl text-ink-muted hover:bg-white/60 hover:text-ink", children: children }));
}
