import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CalendarClock, Check, FileText, Plus, ShieldCheck } from 'lucide-react';
import { GlassSurface } from '../../design-system';
import { openDoc } from '../../state/docViewerStore';
import { toast } from '../../state/toastStore';
export function EvidenceScopeCard({ evidencePack, grant, }) {
    const g = grant;
    return (_jsxs(GlassSurface, { tone: "strong", className: "flex h-full flex-col gap-4 p-6", children: [_jsxs("header", { className: "flex items-center gap-2", children: [_jsx("span", { className: "grid size-7 place-items-center rounded-xl bg-brand-soft text-brand-ink", children: _jsx(FileText, { className: "size-4" }) }), _jsx("h3", { className: "font-display text-base font-bold text-ink", children: "Evidence pack" })] }), _jsx("ul", { className: "flex flex-col gap-2", children: evidencePack.map((e) => (_jsx("li", { children: _jsxs("button", { type: "button", onClick: () => openDoc({ name: e.docName, kind: 'evidence', context: `${e.factor} · ${e.detail}` }), className: "flex w-full items-center gap-3 rounded-2xl bg-white/55 p-3 text-left ring-1 ring-white/60 hover:bg-white", children: [_jsx("span", { className: "grid size-9 shrink-0 place-items-center rounded-xl bg-danger-soft text-danger", children: _jsx(FileText, { className: "size-4" }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("p", { className: "truncate text-[12.5px] font-bold text-ink", children: [e.factor, " \u00B7 ", e.docName] }), _jsx("p", { className: "truncate text-[11px] text-ink-muted", children: e.detail })] }), _jsx("span", { className: "shrink-0 rounded-lg bg-white/80 px-2 py-0.5 text-[10.5px] font-bold text-brand ring-1 ring-white/70", children: "View" })] }) }, e.id))) }), _jsxs("div", { className: "mt-auto rounded-2xl bg-white/55 p-4 ring-1 ring-white/60", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(CalendarClock, { className: "size-4 text-warning" }), _jsxs("span", { className: "text-[13px] font-bold text-ink", children: ["Access expires in ", g.expiresInDays, " days"] })] }), _jsx("ul", { className: "mt-2 flex flex-wrap gap-1.5", children: g.dataCategories.map((c) => (_jsxs("li", { className: "inline-flex items-center gap-1 rounded-full bg-white/80 px-2 py-0.5 text-[10.5px] font-semibold text-ink-soft ring-1 ring-white/70", children: [_jsx(Check, { className: "size-3 text-success" }), " ", c] }, c))) }), _jsxs("p", { className: "mt-2 inline-flex items-center gap-1.5 text-[11px] font-medium text-ink-muted", children: [_jsx(ShieldCheck, { className: "size-3.5" }), " ", g.scopeNote] }), _jsxs("button", { type: "button", onClick: () => toast({ tone: 'info', title: 'Request sent', body: 'Acme Insurance will review your request for additional scope.' }), className: "mt-3 inline-flex items-center gap-1.5 rounded-xl bg-white/80 px-3 py-1.5 text-[11.5px] font-bold text-brand ring-1 ring-white/70 hover:bg-white", children: [_jsx(Plus, { className: "size-3.5" }), " Request more access"] })] })] }));
}
