import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from '@tanstack/react-router';
import { Flame, Play, Target } from 'lucide-react';
import { AreaChart, ConfidenceChip, GlassSurface, MoneyCell, cn } from '../../design-system';
import { seedOperatorThroughput, seedResume } from '../../seed/operatorHome';
// "Resume where I left off" + throughput, combined into one motivating card.
export function ResumeThroughputCard({ throughput = seedOperatorThroughput, resume = seedResume, }) {
    const t = throughput;
    const r = resume;
    const goalPct = Math.min(1, t.clearedToday / t.dailyGoal);
    return (_jsxs(GlassSurface, { tone: "strong", className: "flex h-full flex-col gap-5 p-6", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[12px] font-semibold text-ink-muted", children: "Resume where you left off" }), _jsxs(Link, { to: "/reconciliation", className: "group mt-2 flex items-center gap-4 rounded-3xl bg-gradient-to-br from-brand/95 to-brand-ink/95 p-4 ring-1 ring-white/25", children: [_jsx("span", { className: "grid size-12 shrink-0 place-items-center rounded-2xl bg-white/20 text-white", children: _jsx(Play, { className: "size-5 fill-current" }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "truncate text-[15px] font-bold text-white", children: r.party }), _jsx(ConfidenceChip, { score: r.confidence })] }), _jsx("p", { className: "truncate text-[12px] font-medium text-white/80", children: r.note })] }), _jsx(MoneyCell, { amount: r.amount, size: "lg", className: "!text-lg text-white" })] })] }), _jsxs("div", { className: "flex items-end justify-between gap-4", children: [_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[12px] font-semibold text-ink-muted", children: "Cleared today" }), _jsxs("div", { className: "flex items-baseline gap-2", children: [_jsx("span", { className: "font-display text-4xl font-bold leading-none text-ink tabular", children: t.clearedToday }), _jsxs("span", { className: "text-[13px] font-semibold text-ink-muted", children: ["/ ", t.dailyGoal, " goal"] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "inline-flex items-center gap-1 rounded-full bg-warning-soft px-2.5 py-1 text-[11px] font-bold text-warning", children: [_jsx(Flame, { className: "size-3.5" }), " ", t.streakDays, "-day streak"] }), _jsxs("span", { className: "inline-flex items-center gap-1 rounded-full bg-success-soft px-2.5 py-1 text-[11px] font-bold text-success", children: [_jsx(Target, { className: "size-3.5" }), " ", Math.round(goalPct * 100), "%"] })] })] }), _jsx("div", { className: "h-2 overflow-hidden rounded-full bg-ink/8", children: _jsx("div", { className: cn('h-full rounded-full bg-gradient-to-r from-brand to-ai'), style: { width: `${goalPct * 100}%` } }) }), _jsxs("div", { className: "flex flex-col gap-1", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-[12px] font-semibold text-ink-muted", children: "This week" }), _jsxs("span", { className: "text-[12px] font-semibold text-ink", children: [_jsx("span", { className: "tabular", children: t.clearedMonth.toLocaleString() }), " this month"] })] }), _jsx("div", { className: "min-h-[120px] flex-1", children: _jsx(AreaChart, { xLabels: [...t.weekLabels], series: [{ name: 'Cleared', color: '#16a37b', data: [...t.weekSeries] }], height: 130, guideOnHover: true }) })] })] }));
}
